### PR TITLE
Project Operations via the scripts mechanism

### LINKED ISSUE #156: Add drush updb and fra as an update task
I recently experienced a situation where I merged in a branch that contained an update hook. I ran 'grunt'  to rebuild the site, but the site failed due to a missing table column. I think it'd be worth adding an update task that can run on site builds. This would be handy as code is deployed to various environments.

### PR DESCRIPTION
**Pull request by grayside**
This change adapts the mechanism used for the new Theme Scripts system to support simple project-level operations via simple Gruntconfig.json settings. These can be one-liners entirely contained in the configuration, or they could call out to shell scripts elsewhere in the repository.

If you configure some scripts and run `grunt help` you will see each script displayed in the Operations section.

The documentation has had a first pass, but I think it's getting confusing. Also, I think this needs a bit more test coverage, hence the WIP flag.

I've deliberately avoided setting any default scripts, but there's a lot of potential for gadget to generate a set of good starting ones by prompting for a profile name and maybe a couple other questions. I'll file some issues in the gadget queue based on this once we get it in.

Fixes #156, #98.

### CODE REVIEW

File: test/library.js [hunk 1]
```diff
@@ -25,3 +25,60 @@ describe('Utility Functions', function() {
     });
   });
 });
+
+describe('Initialization', function() {
+  var grunt = require('grunt');
```
Comment (grayside) [inline test/library.js]: Woo-hoo, integration testing!

File: README.md [hunk 2]
```diff
@@ -77,6 +77,7 @@ These environment variables will override other options.
 * `GDT_DOMAIN`: Specify the base URL for live system testing. Falls back to a
 setting in the project's Gruntconfig.json, then hostname if not set.
 * `GDT_QUIET`: If evaluated truthy, will suppress all desktop notifications.
+* `GDT_SITE_ALIAS`: Configure the default Drush site alias for the project.
```
Comment (arithmetric) [inline README.md]: Should GDT_INSTALL_PROFILE be documented here too?

File: README.md [hunk 3]
```diff
@@ -77,6 +77,7 @@ These environment variables will override other options.
 * `GDT_DOMAIN`: Specify the base URL for live system testing. Falls back to a
```
Comment (arithmetric) [inline README.md]: How does GDT_DOMAIN interact with GDT_SITEURLS? Should GDT_SITEURLS be documented here?

File: CONFIG.md [hunk 4]
```diff
@@ -478,12 +479,52 @@ from the project directory when building a package. The above includes README
...
+but facilitates creating lightweight commands or callouts to the shell for more
+advanced scripts you want easily run on the project by the entire team.
+
+This should remind you of the **Themes Scripts** described above.
+
+```
+{
+  "scripts": {
+    "install": "drush <%= config.alias %> install <%= config.profile %> -yv"
+    "update": "drush <%= config.alias %> updatedb -yv && drush <%= config.alias %> features-revert-all -yv"
```
Comment (arithmetric) [inline CONFIG.md]: Could we expose the Drush command path defined in Gruntconfig.json, particularly to ensure we are by default using the version installed by composer?

File: CONFIG.md [hunk 5]
```diff
@@ -478,12 +479,52 @@ from the project directory when building a package. The above includes README
...
+
+The Alias and Profile is specified per the rules for **Magic Configuration**.
+
+**alias**: The Drush Site Alias. This is computed as a helper for use in
+project oeprations, but is not yet applied as part of other tasks. Defaults to
+`@<domain>`. The environment variable is `GDT_SITE_ALIAS`.
+
+**profile**: The Drupal installation profile, this will be used to configure the
+behavior of the drush:liteinstall task. Defaults to `standard`.
+WARNING: drush:liteinstall is an internal task and is likely to be deprecated in
```
Comment (arithmetric) [inline CONFIG.md]: Let's remove this warning. We're offering another use case for the variable, and it doesn't seem in the spirit of semver.

File: test/library.js (hunk 1 above)
Comment (arithmetric) [inline test/library.js]: :+1:

**Comment by arithmetric** [comment]
Overall, this looks great. I added some comments and questions above.

File: README.md (hunk 2 above)
Comment (grayside) [inline README.md]: I can't recall my full reasoning, but I moved the GDT_INSTALL_PROFILE documentation to be alongside the profile config property. Do we want duplicate mention?

File: README.md (hunk 3 above)
Comment (grayside) [inline README.md]: Should we consolidate all environment variables to be discussed in both places? The relationship between DOMAIN and SITEURLS is discussed with the config explanation. Essentially, your SITEURLS should be configured to use the domain token.

File: CONFIG.md (hunk 4 above)
Comment (grayside) [inline CONFIG.md]: Good point. The only downside is how soupy this starts to look:

```
<%= config.drush.cmd %> <%= config.alias %> install <%= config.profile %> -yv
```

It also seems like a likely error users will make in their own configurations.

What if we automatically replace `drush` in the configuration with our vendored version unless it's preceded by a !, such as `!drush`?

File: lib/init.js [hunk 6]
```diff
@@ -39,7 +44,10 @@ module.exports = function(grunt) {
     if (grunt.config('config.siteUrls') === undefined)
       grunt.config('config.siteUrls', {});
 
-    grunt.config('config.domain', module.domain());
+    grunt.config('config.domain', module.magic('domain') || require('os').hostname());
+    grunt.config('config.alias', module.magic('alias', 'SITE_ALIAS') || '@' + grunt.config('config.domain'));
+    grunt.config('config.project.profile', module.magic('profile', 'INSTALL_PROFILE') || 'standard');
```
Comment (grayside) [inline lib/init.js]: Initially this was "config.profile", but since grunt install added config.project.profile I switched this. However, the "magic" picks up on gdt.profile, so maybe one or the other needs a further change.

File: test/test_assets_d8/Gruntconfig.json [hunk 7]
```diff
@@ -26,12 +26,17 @@
...
+    "echo": "echo 'operational scripts run'",
+    "post-echo": "echo 'post-op script'"
+  },
   "themes": {
     "example_theme": {
       "path": "<%= config.srcPaths.drupal %>/themes/example_theme",
       "compass": true,
       "scripts": {
-        "write": "echo 'scripts run'"
+        "echo": "echo 'theme scripts run in '$(basename $(pwd))"
```
Comment (grayside) [inline test/test_assets_d8/Gruntconfig.json]: Expanded test coverage to make sure theme operations run in the theme directory.
